apiVersion: v1
kind: ConfigMap
metadata:
  name: zeebe-exporter-config
  namespace: default
data:
  exporters.json: |
    {
      "exporters": [
        {
          "id": "demo",
          "className": "com.example.demo.DemoExporter",
          "args": {
            "param1": "value1",
            "param2": "value2"
          }
        }
      ]
    }
